<Project>
  <PropertyGroup>
    <Version>5.4.1</Version>
    <AssemblyVersion>5.4.1.0</AssemblyVersion>
    <FileVersion>5.4.1.0</FileVersion>
    <InformationalVersion>5.4.1-community</InformationalVersion>
    <Company>NRTX Labs</Company>
    <Product>TROY Tweaks Windows Optimizer (Community Edition)</Product>
    <Copyright>Copyright © 2026 NRTX Labs</Copyright>
  </PropertyGroup>
</Project>
